#!/bin/bash

files=$(ls twemoji/assets/svg | awk '{ print length, $0 }' | sort -n -s -r | cut -d" " -f2-)
output=twemoji.go

# Start the Go code output
echo "// Code generated by go generate; DO NOT EDIT." > $output
echo "" >> $output
echo "package emojify" >> $output
echo "" >> $output

echo "var twemojiFiles = []string{" >> $output
for file in $files; do
    echo "    \"$file\"," >> $output
done
echo "}" >> $output

gofmt -w $output
