#!/bin/bash

files=$(ls twemoji/assets/svg | awk '{ print length, $0 }' | sort -n -s -r | cut -d" " -f2-)
output=twemoji.go


echo "// Code generated by go generate; DO NOT EDIT." > $output
echo "" >> $output
echo "package emojify" >> $output
echo "" >> $output

ver=$(cd twemoji; git describe --tags --abbrev=0)
echo "// Version is the Twemoji library version." >> $output
echo "const Version = \"${ver:1}\"" >> $output

echo "var twemojiFiles = []string{" >> $output
for file in $files; do
    echo "    \"$file\"," >> $output
done
echo "}" >> $output

gofmt -w $output
